config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  # resources :blogs, only:[:show, :index, :new, :create, :edit, :update, :destroy]
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length:{minimum:6, maximum:100}
  validates :description, presence: true, length:{minimum:12, maximum:1000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # def home
  #   render html: 'Hello World!'
  # end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def show
    @blog = Blog.find(params[:id])
  end

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params.require(:blog).permit(:title, :description))
    if @blog.save
      flash[:notice] = "Blog is created successfully"
      redirect_to blogs_path
      # redirect_to @blog
    else
      render 'new'
    end
    # redirect_to blog_path(@blog)
    # render plain: @blog.inspect
  end


  def update
    @blog = Blog.find(params[:id])
    if @blog.update(params.require(:blog).permit(:title, :description))
      flash[:notice] = "Blog is updated successfully"
      # redirect_to blogs_path
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/blogs/edit.html.erb
<h3>Editing blog</h3>

<% if @blog.errors.any? %>
  <h3>The following errors are occured-</h3>

  <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li>
        <%= msg  %>
      </li>
    <% end %>
  </ul>

<% end %>

<%= form_with(model:@blog, local:true) do |f| %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/blogs/index.html.erb
<h2>Blog listing page</h2>


<table>
  <thead>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3">Action</th>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr style="border:1px solid #000; background-color:#ececec">
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog_path(blog.id) %></td>
        <td><%= link_to 'edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Delete', blog_path(blog.id), method: :delete, data:{ confirm: "Are you sure, you want to delete?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new blog', new_blog_path() %>
</p>

app/views/blogs/new.html.erb
<h3>Posting blog</h3>

<% if @blog.errors.any? %>
  <h3>The following errors are occured-</h3>

  <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li>
        <%= msg  %>
      </li>
    <% end %>
  </ul>

<% end %>

<%= form_with scope: :blog, url: blogs_path, local:true do |f| %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>


<p>
  <%= link_to 'Return to blogs', blogs_path() %>
</p>

app/views/blogs/show.html.erb
<h2>Blog: <%= @blog.id %></h2>

<p><b>Title:</b><%= @blog.title %></p>
<p><b>Description:</b> <%= @blog.description %> </p>
<p><b>Created at:</b> <%= @blog.created_at %> </p>
<p><b>Updated at:</b> <%= @blog.updated_at %> </p>


<p>
  <%= link_to 'Edit', edit_blog_path(@blog) %>
  &nbsp;
  <%= link_to 'Back', blogs_path() %>
  &nbsp;
  <%= link_to 'Delete', blog_path(@blog.id), method: :delete, data:{ confirm: "Are you sure, you want to delete?"}  %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewRubyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About page working</h2>

app/views/pages/home.html.erb
<section>
  <h2>Home page working</h2>
</section>